### ISSUE TITLE
No Stick Detection on Windows 8.1

### ISSUE THREAD

**Issue by JandCandO** [AlexanderDzhoganov/ksp-advanced-flybywire#26]
I downloaded AFBW version 1.4.5 onto KSP 0.90 (32 bit) via CKAN and AFBW doesn't detect my Logitech Extreme 3D Pro Joystick. I'm running Windows 8.1.

I deleted the .xml file in the mod folder multiple times, each time restarting KSP. I even restarted my computer and that didn't let AFBW detect the joystick.

Here is the output log: http://pastebin.com/d4G7qXtV

Here is the generated .xml file: http://pastebin.com/PrBZfyVr

This is my GameData Folder:
![GameData Folder](http://i.imgur.com/NYDhbXn.png)

**Comment by rschuetzler** [comment]
I'm in the same boat. It will detect my XBox 360 controller, but not the Logitech joystick.

**Comment by ddaf** [comment]
Sadly Windows 8 support is not in yet. It was attempted in the next-to-latest version but led to too many negative side-effects and performance-impacts. Hopefully Win8 support will be done properly soon.

**Comment by DeamonSix** [comment]
Same problem here. X-55 is not recognized but Xbox360 controller is. Actualy the 360 controller is shown twice. Once properly as XInput and again as SDL with unnamed controls. I also have the overwriting config problem.

Win 8.1 Pro x64
KSP 0.90 x86
AFBW 1.4.6 x86 (via ckan)

https://www.dropbox.com/s/xia2x8q7yst1zu9/advanced_flybywire_config_v21.xml?dl=0
https://www.dropbox.com/s/2t6xraiel8tcv9w/output_log.txt?dl=0

![ksp_gamedata_20150201](https://cloud.githubusercontent.com/assets/10803443/5995313/d52dd30e-aa5d-11e4-98ad-d2c1a71f5add.png)

**Comment by NJAldwin** [comment]
Is this closed because it is fixed?

**Comment by rschuetzler** [comment]
@NJAldwin I had hoped so, but I'm still not seeing my joystick in-game.

**Comment by NJAldwin** [comment]
@AlexanderDzhoganov any insight into why this was closed?

**Comment by AlexanderDzhoganov** [comment]
Sorry, this is definitely not fixed I must have closed it by mistake.

**Comment by Vespian-xx** [comment]
@AlexanderDzhoganov - Just expressing my interest in this issue being closed. I'd love to use my joystick with the proper support this mod brings in KSP 1.02 and Windows 8.1 x64.

**Comment by Oungawak** [comment]
Someone said that deleting "settings.cfg" solve this issue, and for me it worked. I thought this was probably linked to a specific setting and the only thing I changed that seems to cause troubles is... "Texture Quality" when set to "Full Res". Why!? I have no idea why this setting would break the mod, but now everything works fine.

My config :
- Windows 8.1 x64
- Saitek X-55 Rhino (Stick + Throttle)
- KSP v1 x86
- Advanced Fly-By-Wire v1.5.1

**Comment by BahamutoD** [comment]
I can confirm that with Windows 8, my joysticks did not show up when Texture Quality was at Full Res.
I set it to Half Res and restarted KSP, and now everything shows up.
